[formatter.markdown]
command = "dprint"
options = ["fmt"]
includes = ["*.md"]

[formatter.json]
command = "dprint"
options = ["fmt"]
includes = ["*.json"]

[formatter.toml]
command = "dprint"
options = ["fmt"]
includes = ["*.toml"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]
